In [4]:
import random
import numpy

# 1
# a)
random.seed(123)
n = 10000
numDouble = 0

for i in range(n):
    double6 = False
    for j in range(24):
        die1 = random.randint(1, 6)
        die2 = random.randint(1, 6)
        if die1 == 6 & die2 == 6:
            double6 = True
    if double6:
        numDouble += 1

probDouble = numDouble / n
print("P(double sixes) = ", probDouble)

# P(double sixes) =  0.49196
# For 24 throws the probability of rolling two sixes is ½, the larger the n the closer to ½ the
# observed probability will be.

# ------------------------------------
# b)
random.seed(123)
n = 0
numDouble = 0
probDouble = 0.0

while probDouble <= 0.5:
    n += 1
    double6 = False
    for i in range(n):
        die1 = random.randint(1, 6)
        die2 = random.randint(1, 6)
        if die1 == 6 & die2 == 6:
            double6 = True
    if double6:
        numDouble += 1
    probDouble = numDouble / n

print("min n where P(double sixes) > 0.5 = ", n)


# 2
# a)
def tablelookup(y, p):
    """Sample from y[i] with probabilities p[i]"""
    u = random.random()
    sumP = 0.0
    for i in range(len(p)):
        sumP += p[i]
        if u < sumP:
            return {"yi": y[i], "pi": i}


random.seed(123)
y = [0, 1, 2, 3, 4, 5]
p = [1.0 / 1024, 15.0 / 1024, 90.0 / 1024, 270.0 / 1024, 405.0 / 1024, 243.0 / 1024]
m = 1000000
valuetotal = 0.0
for k in range(m):
    d = tablelookup(y, p)
    valuetotal += d["yi"]
print(valuetotal / m)

# b)
# i)
y = [0, 1, 2, 3, 4, 5]
m = 1000000
valuetotal = 0.0
stepstotal = 0
for k in range(m):
    d = tablelookup(y, p)
    valuetotal += d["yi"]
    stepstotal += d["pi"]
print("i)")
print("value average = ", valuetotal / m)
print("steps average = ", stepstotal / m)

# ii)
y = [5, 4, 3, 2, 1, 0]
p = [243.0 / 1024, 405.0 / 1024, 270.0 / 1024, 90.0 / 1024, 15.0 / 1024, 1.0 / 1024]
m = 1000000
valuetotal = 0.0
stepstotal = 0
for k in range(m):
    d = tablelookup(y, p)
    valuetotal += d["yi"]
    stepstotal += d["pi"]
print("ii)")
print("value average = ", valuetotal / m)
print("steps average = ", stepstotal / m)

# iii)
y = [4, 3, 5, 2, 1, 0]
p = [405.0 / 1024, 270.0 / 1024, 243.0 / 1024, 90.0 / 1024, 15.0 / 1024, 1.0 / 1024]
m = 1000000
valuetotal = 0.0
stepstotal = 0
for k in range(m):
    d = tablelookup(y, p)
    valuetotal += d["yi"]
    stepstotal += d["pi"]
print("iii)")
print("value average = ", valuetotal / m)
print("steps average = ", stepstotal / m)

# iii) gives the fastest table lookup

# 3
print("3.")
# a)
s = numpy.random.normal(0, 1, 1000)

# b)
print("mean = ", numpy.mean(s))
print("standard deviation = ", numpy.std(s))

# mean =  0.000512102519442
# standard deviation =  1.00198864662
# the mean and standard deviation approximate μ and σ, larger the sample size the closer they will be.

# c
numpy.histogram(s)

# c
numpy.histogram(s)

# (array([ 10,  40, 132, 229, 282, 204,  73,  23,   5,   2], dtype=int64),
# array([-3.03595506, -2.32942003, -1.622885  , -0.91634998, -0.20981495,
#         0.49672008,  1.20325511,  1.90979013,  2.61632516,  3.32286019,
#         4.02939522]))


P(double sixes) =  0.4882
min n where P(double sixes) > 0.5 =  65
3.750354
i)
value average =  3.750273
steps average =  3.750273
ii)
value average =  3.750006
steps average =  1.249994
iii)
value average =  3.749319
steps average =  1.064559
3.
mean =  0.000512102519442
standard deviation =  1.00198864662


(array([ 10,  40, 132, 229, 282, 204,  73,  23,   5,   2], dtype=int64),
 array([-3.03595506, -2.32942003, -1.622885  , -0.91634998, -0.20981495,
         0.49672008,  1.20325511,  1.90979013,  2.61632516,  3.32286019,
         4.02939522]))